apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
     app: user-service
     type: user-service
spec:
  template:
     metadata:
       name: user-service
       labels: 
         app: user-service
         type: user-service
     spec:
         containers:
           - name: nodejsapp-erp
             image: "felipenascimento26/0.0.1"
  replicas: 1
  selector:
    matchLabels:
      type: user-service

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  type: LoadBalancer  
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 80
      nodePort: 30000